### ISSUE TITLE
Timeline should be zoomable

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue-datavis#14]
Add a slider to select range of years. Related: #13

**Comment by pkiraly** [comment]
I agree. Instead of a slider Graphana and Kibana tools allow you to select an area of a chart, and you can zoom in. I like that solution (I will add here a link when I find a good example).

**Comment by pkiraly** [comment]
In d3.js this selection can be done with "brush": see documentation at https://d3js.org/d3-brush, example 1: https://observablehq.com/@d3/brush-snapping-transitions, example 2: https://observablehq.com/@d3/click-to-recenter-brush

**Comment by pkiraly** [comment]
Here is how it looks like right now. The bars are clickable at the upper chart.
![goethe sammlung2](https://github.com/pkiraly/qa-catalogue-datavis/assets/218218/7b0117b6-ee54-415c-b25d-4f78c9e6ec85)

**Comment by pkiraly** [comment]
If it solves #13 the I close this as well.
