### ISSUE TITLE
Add visualisation: cataloging timeline

### ISSUE THREAD

**Issue by nichtich** [pkiraly/qa-catalogue-datavis#15]
Show date of cataloging instead date of publication.

**Comment by pkiraly** [comment]
I would say: two timeline, one for publication, another one for cataloguing, and a third one combining the two.

What is the PICA field for the cataloguing date?

**Comment by nichtich** [comment]
The PICA field is [001A0](https://format.k10plus.de/k10plushelp.pl?cmd=kat&katalog=Standard&val=0200) but it contains ILN and `DD-MM-YY` separated by `:` so the Solr indexing would need to be adjusted first.

The history of cataloging being part of QA catalogue requires further processing and generation of an image but cannot directly retrieved from Solr index, can it?

I'd first focus on visualisation that only require some Solr queries to existing index.

**Comment by pkiraly** [comment]
For multi million results it is slow, but for real queries we can extract it in a reasonable amount of time. I have two questions:

1. What is the rule for the year part of the date?

`05-10-21` -- should be logically interpreted as 2021, and `05-06-86` as 1986, but do you have a clear threshold value to decide from which year it is 20th or 21 century? I expect that there will be typos, so a hypothetical 05-10-61 should be interpret as 1961 or 2061? I have the same problem with MARC21, where the standard does not have a guidance.

2. What would be the ideal precision? Day, month or year?

**Comment by pkiraly** [comment]
for the 1st question: it seems the earliest date is 01-01-71 and that must be interpreted as "unknown date" or "in the very old times" because the earliest terms look like
```
    "1971-01-01": 424354,
    "1972-05-15": 1,
    "1972-06-12": 2,
    "1972-06-24": 1,
    "1972-06-26": 2,
    "1972-07-10": 1,
```

**Comment by nichtich** [comment]
I think grouping by year is enough to start with.

**Comment by pkiraly** [comment]
I close it now. We should improve it later by
- improving the Solr indexing by separating of date component and ILN. Date might be indexed in two fields: year and date. In both cases I guess it would worth to normalize date (as YYYY-MM-DD, and YYYY) at indexing time, and do not index as is.
- then add link to search result page
- and we can also add caching for searches that take too much time
